version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: