version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-app-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host